language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t asifhdocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true asifhdocker/react-test npm test

after_success:
  - docker build -t asifhdocker/multi-client ./client
  - docker build -t asifhdocker/multi-nginx ./nginx
  - docker build -t asifhdocker/multi-server ./server
  - docker build -t asifhdocker/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
  # Take those images and push them to docker hub
  - docker push asifhdocker/multi-client
  - docker push asifhdocker/multi-nginx
  - docker push asifhdocker/multi-server
  - docker push asifhdocker/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-161727703880
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
