language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t asifhasan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true asifhasan/react-test npm test

after_success:
  - docker build -t asifhasan/multi-client ./client
  - docker build -t asifhasan/multi-nginx ./nginx
  - docker build -t asifhasan/multi-server ./server
  - docker build -t asifhasan/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
  # Take those images and push them to docker hub
  - docker push asifhasan/multi-client
  - docker push asifhasan/multi-nginx
  - docker push asifhasan/multi-server
  - docker push asifhasan/multi-worker
